---
title: "NLP-evidence"
author: "Justina Razanauskaite"
date: "2024-12-22"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(readxl, dplyr, ggplot2)
```

Load data:

```{r}
# Read an Excel file
# File was downloaded from the paper, and renamed to this one:
data <- read_excel("Experiment_1.xlsx")
```


```{r}
# Remove unnecessary columns

data <- data %>% select(-c(1, 3, 4, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25, 26, 28, 29, 31, 32, 34, 35))

# Select the first 11 columns

data <- data[, 1:11]

```

Calculating the result:

```{r}
data <- data %>%
  mutate(across(everything(), ~ ifelse(is.na(.), "w", .)))

# Count Lure and Reflect responses for each participant

summary <- data %>%
  rowwise() %>%
  summarize(
    RandomID = RandomID,
    Lure = sum(c_across(starts_with("VCRTCode")) == "Lure"),
    Reflect = sum(c_across(starts_with("VCRTCode")) == "Reflect"),
    Wrong = sum(c_across(starts_with("VCRTCode")) == "w")
  )

# Calculate averages

averages <- summary %>%
  summarize(
    Avg_Lure = mean(Lure),
    Avg_Reflect = mean(Reflect),
    Avg_wrong = mean(Wrong)
  )

print(averages)

averages <- tibble(
  Response = c("Lure", "Reflect", "Other"),
  Average = c(5.616162, 3.59596, 0.06060606)
)
```

Calculating response results for Byrd et. al (2023):

```{r}
averages <- averages %>%
  arrange(desc(Average))

# Plot the data
ggplot(averages, aes(x = reorder(Response, -Average), y = Average, fill = Response)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = round(Average, 2)),   
            vjust = -0.3,                   
            size = 4) +
  labs(title = "Average Responses: 10-item CRT, Byrd et al. (2023)", x = "Response", y = "Average") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")  # Center and bold title
  ) +
  scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, by = 1))
```

Calculating response results for Li et. al (2024):

```{r}
# It is taken straight from the paper.
mean_correct <- (62.1 + 24.9 + 54.8 + 45.6 + 55.6 + 33 + 38.3 + 56.7 + 40.2) / 9 # 45.6
mean_correct

mean_intuitive <- (33 + 72 + 24.1 + 11.1 + 20.7 + 54.4 + 47.1 + 21.8 + 50.6) / 9 # 37.2
mean_intuitive

mean_incorrect <- (5 + 3.1 + 21.1 + 43.3 + 23.8 + 12.6 + 14.6 + 21.5 + 9.2) / 9 # 17.13
mean_incorrect

averages1 <- tibble(
  Response = c("Intuitive", "Correct", "Other"),
  Average = c(37.2, 45.68889, 17.13333)
)

averages1 <- averages1 %>%
  arrange(desc(Average))

# Plot the data
ggplot(averages1, aes(x = reorder(Response, -Average), y = Average, fill = Response)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = round(Average, 2)),   
            vjust = -0.3,                   
            size = 4) +
  labs(title = "Average Responses: 9-item CRT, Li et al. (2024)", x = "Response", y = "Average (%)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")  # Center and bold title
  ) +
  scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 10))
```

